version: '3.9'
services:
  db:
    image: postgis/postgis:12-master
    container_name: "{{cookiecutter.project_snake}}_db"
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB={{cookiecutter.project_slug}}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/app
      - /tmp:/tmp
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - docker.env
    depends_on:
      - db
volumes:
  db_data:
