---
Resources:
  LockingDbTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Join ["-", [ !Ref "AWS::StackName", 'locks' ]]
      Tags:
        - Key: user:project
          Value: osn-platform
        - Key: user:stage
          Value: ${self:provider.stage}
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      KeySchema:
        - AttributeName: "LockName"
          KeyType: "HASH"
      AttributeDefinitions:
        - AttributeName: "LockName"
          AttributeType: "S"
      TimeToLiveSpecification:
        AttributeName: "TimeToLive"
        Enabled: True

Outputs:
  LockingDbTableName:
    Value: !Ref LockingDbTable
    Export:
      Name: !Join ["-", [ !Ref "AWS::StackName", "locks-table-name" ]]
