---
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete  # Delete or Retain
    Properties:
      BucketName: ${self:provider.stage}.storage.osn.100procentlokaal.be
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
      Tags:
        - Key: user:project
          Value: osn-platform
        - Key: user:domain
          Value: ${self:custom.infrastructure.${self:provider.stage}.cdnDomainName, self:custom.infrastructure.default.cdnDomainName}
        - Key: user:stage
          Value: ${self:provider.stage}

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Join ['', ['arn:aws:s3:::', !Ref Bucket, '/*']]
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
