---
Resources:
  DBSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ${self:custom.infrastructure.${self:provider.stage}.application.databaseSecretName, self:custom.infrastructure.default.application.databaseSecretName}
      Description: 'RDS credentials for ${self:service}-${self:provider.stage}'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  DBInstanceSecretTargetAttachment:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Properties:
      SecretId: !Ref DBSecret
      TargetId: !Ref DBInstance
      TargetType: 'AWS::RDS::DBInstance'

  GeoDBSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: ${self:custom.infrastructure.${self:provider.stage}.application.geoDatabaseSecretName, self:custom.infrastructure.default.application.geoDatabaseSecretName}
      Description: 'RDS GEO credentials for ${self:service}-${self:provider.stage}'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  GeoDBClusterSecretTargetAttachment:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Properties:
      SecretId: !Ref GeoDBSecret
      TargetId: !Ref GeoDBCluster
      TargetType: 'AWS::RDS::DBCluster'

Outputs:
  DBSecret:
    Description: DBSecret Arn
    Value: !Ref DBSecret

  GeoDBSecret:
    Description: GeoDBSecret Arn
    Value: !Ref GeoDBSecret
